---
# tasks file for apps-server
#- name: Create hostnames
#  include_tasks: hosts.yml

#- name: Set php_ver 7.4 if Ubuntu 20.04
#  set_fact:
#    php_ver: 7.4
#  when: ansible_distribution_version == "20.04"

#- name: Set php_ver 8.1 if Ubuntu 20.04
#  set_fact:
#    php_ver: 8.1
#  when: ansible_distribution_version == "22.04"

- name: Install Nginx and congig
  include_tasks: nginx.yml

- name: Install php
  include_tasks: php.yml
  
- name: Install wordpress
  include_tasks: wordpress.yml
